export const PATH = {
  MAIN: '/',
  REGISTER: '/registration',
  MAINBOARD: '/mainboard',
  DASHBOARD: '/mainboard/dashboard',
  DEAL: '/mainboard/deal',
  DEAL_DETAILS: '/mainboard/deal/:dealId',
  CONTRIBUTION: '/mainboard/contribution',
  DISCOVER: '/mainboard/discover',
  DISCOVER_DETAILS: '/mainboard/discover/:projectId',
  GOVERNANCE: '/mainboard/governance',
  ADMINLOGIN: '/kommdao-admin',
  ADMINMAINBOARD: '/admin-mainboard',
  USERAPPLICANTS: '/admin-mainboard/user/applicants',
  USERMEMBERS: '/admin-mainboard/user/members',
  USERCOMMITTES: '/admin-mainboard/user/committes',
  USERKOHORTS: '/admin-mainboard/user/kohorts',
  DEALROOM: '/admin-mainboard/deal/dealroom',
  DEALINTEREST: '/admin-mainboard/deal/dealinterest',
  ADMINDISCOVER: '/admin-mainboard/discover',
  PROFILE: '/mainboard/dashboard/profile',
  PROFILE_UPDATE: '/mainboard/dashboard/profile/profile-update',
  DEAL_INTEREST: '/mainboard/deal/deal-details/:dealId/interest',
};
