export const PATH = {
  MAIN: '/',
  REGISTER: '/registration',
  MAINBOARD: '/mainboard',
  DASHBOARD: '/mainboard/dashboard',
  DEAL: '/mainboard/deal',
  CONTRIBUTION: '/mainboard/contribution',
  DISCOVER: '/mainboard/discover',
  GOVERNANCE: '/mainboard/governance',
  ADMINLOGIN: '/kommdao-admin',
  ADMINMAINBOARD: '/admin-mainboard',
  USERAPPLICANTS: '/admin-mainboard/user/applicants',
  USERMEMBERS: '/admin-mainboard/user/members',
  USERCOMMITTES: '/admin-mainboard/user/committes',
  USERKOHORTS: '/admin-mainboard/user/kohorts',
};
